# Install a Python virtual environment with all requirements
FROM ubuntu:24.04 AS builder

ENV LANG=C.UTF-8
COPY requirements*.txt /

RUN apt-get update && \
    apt-get -y upgrade && \
    # Install the necessary system packages
    apt-get install -y python3 python3-pip python3-venv && \
    apt-get clean && \
    # Install the virtual environment and the requirements
    python3 -m venv --upgrade-deps /python-venv && \
    /python-venv/bin/pip3 install -r /requirements.txt && \
    # Remove files not needed for running the app from the virtual environment
    /python-venv/bin/pip3 uninstall -y pip && \
    rm -rf \
        /python-venv/include \
        /python-venv/lib/python3*/site-packages/__pycache__

# Setup the final image with the application code and the created virtual environment
FROM ubuntu:24.04 AS final
LABEL org.opencontainers.image.source="https://github.com/LiquidAI-project/wasmiot-supervisor"

ENV LANG=C.UTF-8
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y python3-minimal && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /python-venv /python-venv
COPY . /app/

WORKDIR /app
CMD ["/python-venv/bin/python3", "-m", "host_app"]
