name: Supervisor Docker Image

on:
  workflow_dispatch:
  push:
    branches: 
      - "main"

env:
  IMAGE_NAME: ghcr.io/liquidai-project/wasmiot-supervisor
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Log into registry
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push fileserv
        uses: docker/build-push-action@v4
        with:
          context: .          
          target: base
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Build and push devcontainer
        uses: devcontainers/ci@v0.3
        with:
          eventFilterForPush:
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: devcontainer
